# Generated by Django 4.1.1 on 2022-10-09 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='description',
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
